spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogdb
    username: postgres
    password: 95628
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: BlogApp

server:
  port: 8080
